### ISSUE TITLE
Running into some possible JNI issues with Raylib

### ISSUE THREAD

**Issue by davidbruce** [Aurel300/ammer#56] opened 2023-03-26 23:37 UTC
I've been trying to follow along with amlib-qoi and make a wrapper for Raylib.  
It appears to work, but it freezes after loading the raylib libraries.  I think it may have something to do with GLFW, but I'm not entirely sure.  

Any ideas on how I can debug this?

Haxe version:
4.3.0 rc1 built from  https://github.com/HaxeFoundation/haxe/tree/10301c8b90fb390ab3d1523510cd86e0bcab31e8

Architecture:
Aarch64 M1 Macos

Ammer:
ammer ammer-core-rewrite branch
ammer-core dev branch

Raylib:
Version 4.5 from tag 4.5.0 (not sure why the output shows 4.6.0-dev)

Java arm64:
openjdk 19.0.2 2023-01-17
OpenJDK Runtime Environment Zulu19.32+13-CA (build 19.0.2+7)
OpenJDK 64-Bit Server VM Zulu19.32+13-CA (build 19.0.2+7, mixed mode, sharing)

Wrapper code src/amlib/raylib/Raylib.hx:
```haxe
package amlib.raylib;

import ammer.ffi.*;

// @:ammer.lib.includePath("../../../native/raylib/raylib/include")
@:ammer.lib.includePath"../../../../../../../../../opt/homebrew/include/")
@:ammer.lib.headers.includeLocal("raylib.h")
@:ammer.lib.frameworks(["Cocoa", "IOKit", "OpenGL", "CoreVideo", "GLUT"])
@:ammer.lib.libraryPaths([
    // "../../../native/raylib/raylib/"
    "../../../../../../../../../opt/homebrew/lib/"
])
class Raylib extends ammer.def.Library<"raylib"> {
    public static function InitWindow(width :Int32, height :Int32, title :String) :Void;
    public static function BeginDrawing() :Void;
    public static function EndDrawing() :Void;
    public static function WindowShouldClose() :Bool;
    public static function CloseWindow() :Void;
}
```

src/Main.hx:
```haxe
package;

import amlib.raylib.*;

function main() {
    Raylib.InitWindow(800, 450, "What");
    while (!Raylib.WindowShouldClose())    // Detect window close button or ESC key
    {
        // Draw
        //----------------------------------------------------------------------------------
        Raylib.BeginDrawing();
        Raylib.EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    Raylib.CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------
}
```

build.hxml:
```haxe
-cp src/
--library ammer
-D ammer.buildPath=build
-D ammer.outputPath=bin
--main Main
--jvm bin/Main.jar
```

Output:
```
INFO: Initializing raylib 4.6-dev
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
```

Expected Output:
```
INFO: Initializing raylib 4.5
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1800 x 1169
INFO:     > Screen size:  800 x 640
INFO:     > Render size:  800 x 640
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 43
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Apple
INFO:     > Renderer: Apple M1 Max
INFO:     > Version:  4.1 Metal - 83
INFO:     > GLSL:     4.10
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds
```

**Comment by Aurel300** [comment] 2023-03-27 13:41
Is the code in Main.hx taken from a Raylib example? (Just to make sure the calls themselves are the ones that are needed.) Does it work the same with another ammer target, such as HL or C++?

**Comment by Aurel300** [comment] 2023-03-27 14:21
Actually, I wonder if the version mismatch is relevant: is there any chance you are compiling against 4.5 headers but using 4.6 at runtime? How do you invoke the JAR? Do you provide a path to where the `dylib` is?

**Comment by davidbruce** [comment] 2023-03-27 14:22
@Aurel300 C++ gave me this exception:
```
/ammer-core/src/ammer/core/plat/Cpp.hx:24: characters 29-34 : Uncaught exception todo
```

The Lua target works though with lua 5.4.4 using my system install of raylib in `/opt/homebrew/lib`:
```
INFO: Initializing raylib 4.5
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 3440 x 1440
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 43
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Apple
INFO:     > Renderer: Apple M1 Max
INFO:     > Version:  4.1 Metal - 83
INFO:     > GLSL:     4.10
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
```

![image](https://user-images.githubusercontent.com/8431078/227968299-67f2be83-484b-45ab-bb61-8b98d3864549.png)

**Comment by davidbruce** [comment] 2023-03-27 14:34
> Actually, I wonder if the version mismatch is relevant: is there any chance you are compiling against 4.5 headers but using 4.6 at runtime? How do you invoke the JAR? Do you provide a path to where the `dylib` is?

Just tried the JVM target again with the same system library as the Lua target and I get the same issue:
```
INFO: Initializing raylib 4.5
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
```

**Comment by Aurel300** [comment] 2023-03-30 19:27
Ok, I can reproduce something similar: compiling and running with HashLink works as expected. On Java, I actually get a stacktrace from the OS when running, mostly complaining that some methods (probably called from within raylib/GLFW) can only be called from the application's "main" thread.

```
+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.
```

Fortunately, I just found [this answer on SO](https://stackoverflow.com/a/44184837), citing the magic argument `-XstartOnFirstThread`. Running the example with `java -XstartOnFirstThread -jar Main.jar` worked. Does it work for you?

**Comment by davidbruce** [comment] 2023-03-31 03:37
That was it!  With how often I am adding `-XstartOnFirstThread` to java configs for SWT you would think I would have thought of that! 

Thank you so much!

I have to ask though, were you doing anything special to get that stack trace?

**Comment by Aurel300** [comment] 2023-03-31 07:46
Great! No, I didn't do anything special. Maybe the behaviour changed across OS versions? Maybe the newer Java version caught the exception raised by the OS but was silent? I'm not sure.

Anyway, I will close this issue now. I will add a note about this flag to the Java section in the manual since there will be other libraries that need this.

I would be happy to hear more about the raylib bindings too, feel free to get in touch on Discord, for example.

**Closed as completed** 2023-03-31 07:46 UTC
